name: Build/Test/Release

on:
  push:
    tags: [ "v*" ]
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  PACKAGE: "clash"

jobs:
  compile:
    name: Compile
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Example
          # when not set, default will be used
          # - os: ubuntu-latest
          #   target: x86_64-unknown-linux-gnu
          #   release-name: x86_64-linux
          #   toolchain: stable
          #   cross: true
          #   file-ext: ""
          #   extra-args: ""
          #   components: ""

          # Linux x86
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            release-name: x86_64-linux
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            release-name: x86_64-linux-musl
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            release-name: i686-linux
          - os: ubuntu-latest
            target: i686-unknown-linux-musl
            release-name: i686-linux-musl
          # Linux arm
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            release-name: aarch64-linux
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            release-name: aarch64-linux-musl
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabi
            release-name: armv7-linux
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            release-name: armv7-linux-hf
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabi
            release-name: armv7-linux-musl
          - os: ubuntu-latest
            target: armv7-unknown-linux-musleabihf
            release-name: armv7-linux-muslhf
          # # Linux mips
          # - os: ubuntu-latest
          #   target: mips-unknown-linux-gnu
          #   release-name: mips-linux
          #   toolchain: nightly
          #   components: rust-src
          #   extra-args: "-Zbuild-std"
          # - os: ubuntu-latest
          #   target: mips-unknown-linux-musl
          #   release-name: mips-linux-musl
          #   toolchain: nightly
          #   components: rust-src
          #   extra-args: "-Zbuild-std"
          # - os: ubuntu-latest
          #   target: mips64-unknown-linux-gnuabi64
          #   release-name: mips64-linux
          #   toolchain: nightly
          #   components: rust-src
          #   extra-args: "-Zbuild-std"
          # - os: ubuntu-latest
          #   target: mips64-unknown-linux-muslabi64
          #   release-name: mips64-linux-musl
          #   toolchain: nightly
          #   components: rust-src
          #   extra-args: "-Zbuild-std"
          # # Linux mipsel
          # - os: ubuntu-latest
          #   target: mipsel-unknown-linux-gnu
          #   release-name: mipsel-linux
          #   toolchain: nightly
          #   components: rust-src
          #   extra-args: "-Zbuild-std"
          # - os: ubuntu-latest
          #   target: mipsel-unknown-linux-musl
          #   release-name: mipsel-linux-musl
          #   toolchain: nightly
          #   components: rust-src
          #   extra-args: "-Zbuild-std"
          # - os: ubuntu-latest
          #   target: mips64el-unknown-linux-gnuabi64
          #   release-name: mips64el-linux
          #   toolchain: nightly
          #   components: rust-src
          #   extra-args: "-Zbuild-std"
          # - os: ubuntu-latest
          #   target: mips64el-unknown-linux-muslabi64
          #   release-name: mips64el-linux-musl
          #   toolchain: nightly
          #   components: rust-src
          #   extra-args: "-Zbuild-std"
          # Need update rustls
          # # Linux risc-v
          # - os: ubuntu-latest
          #   target: riscv64gc-unknown-linux-gnu
          #   release-name: riscv64gc-linux
          #   toolchain: nightly
          # Windows
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            release-name: x86_64-windows
            toolchain: stable
            cross: false
            file-ext: ".exe"
          - os: windows-latest
            target: i686-pc-windows-msvc
            release-name: i686-windows
            file-ext: ".exe"
          # Windows GNU
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            release-name: x86_64-windows-gnu
            cross: true
            file-ext: ".exe"
          # MacOSX
          - os: macos-11 # TODO why 11
            target: x86_64-apple-darwin
            release-name: x86_64-darwin
            cross: false
          - os: macos-13 # TODO why 13
            target: aarch64-apple-darwin
            release-name: aarch64-darwin
            cross: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ matrix.target }}-release-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ matrix.target }}-release

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain || 'stable' }}
          target: ${{ matrix.target }}
          components: ${{ matrix.components }}

      - uses: clechasseur/rs-cargo@v2
        with:
          use-cross: ${{ matrix.cross || 'true' }}
          command: build
          args: --release -p ${{ env.PACKAGE }} --target ${{ matrix.target }} ${{ matrix.extra-args }}

      - name: Rename binary
        run: mv target/${{ matrix.target }}/release/${{ env.PACKAGE }}${{ matrix.file-ext }} ${{ env.PACKAGE }}-${{ matrix.release-name }}${{ matrix.file-ext }}

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.target }}-${{ env.PACKAGE }}
          path: ${{ env.PACKAGE }}-${{ matrix.release-name }}${{ matrix.file-ext }}

  release:
    name: Release
    needs: [compile]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Merge binaries
        uses: actions/upload-artifact/merge@v4
        with:
          name: binaries
          pattern: binary-*

      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: ./packages

      - name: Github stable release
        uses: "mathieucarbou/marvinpinto-action-automatic-releases@master"

        if: startWith(github.ref, "refs/tags/v")
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            packages/*
            LICENSE

      - name: Github nightly release
        uses: "mathieucarbou/marvinpinto-action-automatic-releases@master"
        if: startWith(github.ref, "refs/heads/master")
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "latest"
          files: |
            packages/*
            LICENSE
